env:
  global:
    - CODECOV_TOKEN=$CODECOV_KEY

notifications:
  email:
    on_failure: never
    on_success: never
        
language: java

script:
  - mvn clean install antrun:run sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_KEY -Dsonar.organization=amarteleto

after_success:
  - bash <(curl -s https://codecov.io/bash)
