--TestEntityPersistence
INSERT INTO TB_TEST_ENTITY_PERSISTENCE (SQ_TEEP_SEQUENCE,NM_TEEP_NAME) VALUES (NEXT VALUE FOR SQ_TEEP_SEQUENCE , 'TestEntityPersistence 1')
INSERT INTO TB_TEST_ENTITY_PERSISTENCE (SQ_TEEP_SEQUENCE,NM_TEEP_NAME) VALUES (NEXT VALUE FOR SQ_TEEP_SEQUENCE , 'TestEntityPersistence 2')
INSERT INTO TB_TEST_ENTITY_PERSISTENCE (SQ_TEEP_SEQUENCE,NM_TEEP_NAME) VALUES (NEXT VALUE FOR SQ_TEEP_SEQUENCE , 'TestEntityPersistence 3')
INSERT INTO TB_TEST_ENTITY_PERSISTENCE (SQ_TEEP_SEQUENCE,NM_TEEP_NAME) VALUES (NEXT VALUE FOR SQ_TEEP_SEQUENCE , 'TestEntityPersistence 4')
INSERT INTO TB_TEST_ENTITY_PERSISTENCE (SQ_TEEP_SEQUENCE,NM_TEEP_NAME) VALUES (NEXT VALUE FOR SQ_TEEP_SEQUENCE , 'TestEntityPersistence 5')

--TestEntityPersistenceHibernateChild
INSERT INTO TB_TEST_ENTITY_PERSI_CHILD (SQ_TEPC_SEQUENCE,SQ_TEEP_SEQUENCE,TX_TEEP_TEXT) VALUES (NEXT VALUE FOR SQ_TEPC_SEQUENCE , 4, 'AAAAAA')
INSERT INTO TB_TEST_ENTITY_PERSI_CHILD (SQ_TEPC_SEQUENCE,SQ_TEEP_SEQUENCE,TX_TEEP_TEXT) VALUES (NEXT VALUE FOR SQ_TEPC_SEQUENCE , 4, 'BBBBBB')
INSERT INTO TB_TEST_ENTITY_PERSI_CHILD (SQ_TEPC_SEQUENCE,SQ_TEEP_SEQUENCE,TX_TEEP_TEXT) VALUES (NEXT VALUE FOR SQ_TEPC_SEQUENCE , 4, 'CCCCCC')
INSERT INTO TB_TEST_ENTITY_PERSI_CHILD (SQ_TEPC_SEQUENCE,SQ_TEEP_SEQUENCE,TX_TEEP_TEXT) VALUES (NEXT VALUE FOR SQ_TEPC_SEQUENCE , 4, 'DDDDDD')
INSERT INTO TB_TEST_ENTITY_PERSI_CHILD (SQ_TEPC_SEQUENCE,SQ_TEEP_SEQUENCE,TX_TEEP_TEXT) VALUES (NEXT VALUE FOR SQ_TEPC_SEQUENCE , 4, 'EEEEEE')